### ISSUE TITLE
Please remove all those trackers again!

### ISSUE THREAD

**Issue by IzzySoft** [michaelbel/movies#12]
The version from 11/2018 was completely tracker-free. Now I see the new version comes with 2 ad and 2 analytics modules – plus GMS. Is that really needed? Would you consider making your app clean again?

**Comment by michaelbel** [comment]
Hi, thanks for issue, i didn't know that someone use the app. I think to remove GA and AdMob in the next version.

**Comment by IzzySoft** [comment]
Thanks, that's great! And well, if noone uses it, it won't need them either, would it? :rofl:

Besides: for others to easier find it and have it up-to-date, I've included your app [with my repo](https://apt.izzysoft.de/fdroid/index/apk/org.michaelbel.moviemade) – so it's available using the F-Droid app (with my repo added). I hope that's OK with you.

**Comment by IzzySoft** [comment]
I see you've tagged a new version (1.3.0) – but I cannot find the APK. Could you maybe attach it to the release? Thanks in advance!

**Comment by michaelbel** [comment]
Need to fix one problem with displaying content.

![IMG_20190318_014403_814](https://user-images.githubusercontent.com/16020628/54499126-6f33f280-491f-11e9-8c9d-1bdcb95dc827.jpg)

**Comment by IzzySoft** [comment]
Ah, I see. OK, I will be more patient :smile:

**Comment by michaelbel** [comment]
[Done](https://github.com/michaelbel/Moviemade/tree/master/bin)!

**Comment by IzzySoft** [comment]
Cool! Would you mind attaching the APK to a release then?

**Comment by IzzySoft** [comment]
Thanks for considering! I've meanwhile grabbed the APK manually and updated it in my repo (should show up tomorrow). Please let me know when you switched that to releases, so I turn on auto-update accordingly.

**Comment by dimqua** [comment]
Thanks for the app! It's not feature complete yet, but it has good potential - there aren't much FOSS alternatives.

**Comment by IzzySoft** [comment]
Unfortunately, v1.3.2 brought the problem back – coming with Crashlytics, Firebase, Firebase Analytics, GMS… Couldn't you please provide a privacy friendly version continously?

I hope it was just an accident and you uploaded the wrong APK. I've removed the update from my repo and disabled auto-updates for now. Please let us know when a tracker-free version is available again, @michaelbel – Thanks!

**Comment by michaelbel** [comment]
Do you mean the version without all firebase services? For example crashlytics helps in dev.

**Comment by IzzySoft** [comment]
Yes, as v1.3.1 was, for example. And there are more privacy-friendly libraries for "bug hunting", which give the user a choice and don't log to some data kraken all the time. One example would be [ACRA](https://github.com/acra/acra). Crashlytics etc. might be convenient – but the users pay the price with their privacy.

**Comment by ClintAntone1921** [comment]
![asaaas](https://user-images.githubusercontent.com/66455034/87863045-80649780-c989-11ea-9e3d-1f3cef563bbc.png)
I cannot find this file.

**Comment by GitJamz** [comment]
So a privacy friendly alternative is abandoned?

**Comment by michaelbel** [comment]
nope

**Comment by IzzySoft** [comment]
Good to read you're still having this on your map, @michaelbel – Thanks! Any ETA? Basically, your app was no longer updated in my repo since those trackers were introduced (because of them), and only can be updated again when this issue is solved. So my repo still has v1.3.1 from 7/2019.

**Comment by GitJamz** [comment]
> Good to read you're still having this on your map, @michaelbel – Thanks! Any ETA? Basically, your app was no longer updated in my repo since those trackers were introduced (because of them), and only can be updated again when this issue is solved. So my repo still has v1.3.1 from 7/2019.

Love you Izzy and thank you for your awesome repo. One knows that if the source is Izzy then it has the user integrity in mind.
Keep doing what you do!

@michaelbel please consider removing the trackers from the application. Thank you

**Comment by IzzySoft** [comment]
Oh, completed? Let's check…

```
Offending libs:
---------------
* Crashlytics (/com/crashlytics): NonFreeDep,Tracking
* Google Ads (/com/google/ads): Ads,NonFreeDep
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Google Play Core (/com/google/android/play/core): NonFreeNet,NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Analytics (/com/google/firebase/analytics): NonFreeDep,Tracking
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

8 offenders.
```

So rather `wontfix` :cry:

**Comment by theAkito** [comment]
So, that is why I found this open source app here, yet there is only a Google Play button in the README and I also cannot find it on F-Droid.

Well, what a shame. Won't be using this app, then!

@michaelbel Could've at least released a clean version for F-Droid, while keeping track of Google Play users!
